### ISSUE TITLE
請問還有在更新嗎

### ISSUE THREAD

**Issue by eric31311** [JasonLiTW/tkb-auto-booking#1]
你好, 我最近也面臨tkb訂位問題
但似乎這個code已經不能用了
test.py 無法登入
想請問還有可能再做更新嗎

**Comment by eric31311** [comment]
status return 301

**Comment by JasonLiTW** [comment]
因為手邊已經沒有可用的帳號了，除非能有帳號作測試，不然應該是沒辦法再更新囉
